### ISSUE TITLE
Multiple Insert Slots

### ISSUE THREAD

**Issue by necrogami** [LuziferSenpai/Deep-Storage-Unit#4]
I'm direct inserting via a Tuxego TA Miner and i'm wanting to have maybe 2-4 insert slots so that the miner can dump more resources per load into the DSU before it pulls it into bulk storage i'm currently be limited by how fast the dsu can chew up the incoming ore.

**Comment by LuziferSenpai** [comment]
Will not happen, because it will not work for fluid. And you shouldnt place 400 of them, they update 1 dsu per tick.

**Comment by necrogami** [comment]
400 of what? 1 Beaconed TA Miner can do like 1600 ore per second.

**Comment by LuziferSenpai** [comment]
You know that the input is like 500? And a second is 60 ticks? Its more then enough time

**Comment by necrogami** [comment]
I can easily show you our setup drastically outstrips the input capacity of the dsu. Is there a way to raise the limit?

**Comment by LuziferSenpai** [comment]
I will not rise it, because its not designed to be a chest for a miner, its designed as end storage.

**Comment by necrogami** [comment]
Fine, i'll figure out how to modify this mod for my server's use.

**Comment by necrogami** [comment]
were maxing out around 400 per second not 500 per tick.
