### ISSUE TITLE
on_tick next index slows

### ISSUE THREAD

**Issue by necrogami** [LuziferSenpai/Deep-Storage-Unit#5]
because of how on_tick updates the more dsu's you place down the slower it will intake or out take items. 

I still haven't figured out how to raise the output storage number but with a high overload_multiplier you can at least insert a great deal into the dsu

Doing this fixes the mass of our problems.
```
local on_tick = function()

    for _, unit in pairs( script_data.units ) do
        local index, unit = next( script_data.units, script_data.next_index )

        if index then
            script_data.next_index = index

            unit:update()
        else
            script_data.next_index = nil
        end
    end

end
```

**Comment by LuziferSenpai** [comment]
I did on purpose NOT update all of them per tick!
